/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EbCustomTable: typeof import('everybody-ui').EbCustomTable
  const EbcustomTable: typeof import('everybody-ui').EbcustomTable
}
