/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EbcustomTable: typeof import('everybody-ui')['EbcustomTable']
    ElButton: typeof import('element-plus/es')['ElButton']
  }
}

// For TSX support
declare global {
  const EbcustomTable: typeof import('everybody-ui')['EbcustomTable']
  const ElButton: typeof import('element-plus/es')['ElButton']
}