name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # 2. 安装 pnpm (最新版)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm turbo build check-types
      - run: pnpm turbo check-types build
      - name: Publish Package
        run: |
          # 进入你真正想要发布的 UI 组件库目录
          cd packages/everybody-ui
          
          # 检查该目录下的 package.json 是否已经去掉了 "private": true
          # 并且版本号 (version) 是否已经更新
          npm publish --access public --provenance
